name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Validate terraform modules
    strategy: 
      matrix: 
        module: ["terraform", "pptp_vpn"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: Check terraform module
        run: terraform validate {{ maxtrix.module }}
